# Generated by Django 3.2.15 on 2023-11-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
